LoginReg/urls.py
from django.urls import path
from .views import index, login, registration, logout

app_name = 'LoginReg'

urlpatterns = [
    path('', index, name="index"),
    path('login/', login, name="login"),
    path('logout/', logout, name="logout"),
    path('registration/', registration, name="registration")
]

askcs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('acc/', include('LoginReg.urls')),
    path('ask/', include('beranda.urls')),
]

beranda/urls.py
from django.urls import path
from .views import *
from django.conf.urls.static import static
from django.conf import settings

app_name = 'beranda'
urlpatterns = [
    path('', BlogViews,name='post'),
    path('blog/<slug:slug>/', BlogDetail, name='detail'),
    path('kelas/', BlogDetail, name='test'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    # dilanjutkan ...
]

LoginReg/models.py
from django.db import models

# Create your models here

beranda/models.py
from django.db import models
# Create your models here.

class Blog(models.Model):
    Title = models.CharField(max_length = 300)
    Content = models.CharField(max_length=1000)
    Slug = models.SlugField(max_length=100,unique=True, default ='')
    Date = models.DateTimeField(auto_now_add = True)

    class Meta:
        ordering = ('-Date',)

    def __str__(self):
        return self.Title
    
    def __unicode__(self):
        return u'%s' % self.Title

class Comment(models.Model):
    Post = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='comments')
    Name = models.CharField(max_length=100, default="Unknown")
    Body = models.CharField(max_length=500)
    Created = models.DateTimeField(auto_now_add=True)
    Active = models.BooleanField(default=True)
    Parent = models.ForeignKey('self', on_delete=models.CASCADE, null = True, blank=True, related_name='replies')

    class Meta:
       ordering = ('-Created',)

    def __str__(self):
        return 'Comment By {}'.format(self.Name)

homepage/models.py
from django.db import models

# Create your models here

LoginReg/forms.py
from django import forms
from . import models

beranda/forms.py
from django import forms
from .models import *

class CommentForm(forms.ModelForm):
    Body = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'input',
            'placeholder' : 'Tulis disini...'
        }
    ))
    Name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'input',
            'placeholder' : 'Tulis nama kamu disini...'
        }
    ))
    class Meta:
        model = Comment
        fields = ('Name', 'Body')
        widgets = {
            'Name' : forms.TextInput(attrs={'class':'input'}),
        }

LoginReg/views.py
from django.shortcuts import render, redirect
from . import forms
from datetime import datetime, date
from django.contrib import messages
from django.contrib.auth.models import User, auth

# Create your views here.
def login(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(request,username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('LoginReg:index')
        else:
            if not username:
                return render(request, "login.html", {'confirm':'please fill your username'})
            return render(request, "login.html", {'confirm':'wrong username or password'})
    else:
        return render(request, "login.html")

def index(request):
    return render(request, "index_1.html")

def registration(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        password2=request.POST['password2']
        if not username:
            return render(request, "registration.html", {'confirm':'please fill your username'})
        if password==password2:
            if User.objects.filter(username=username).exists():
                return render(request, "registration.html", {'confirm':'username is not available'})
            else:
                if len(password)<8:
                    return render(request, "registration.html", {'confirm':'please fill your password'})
                user=User.objects.create_user(username=username, password=password)
                user.save()
                return render(request, "registration.html", {'confirm':'user has been created, go to login page'})
        return render(request, "registration.html", {'confirm':'password is not match'})
    else:
        return render(request, "registration.html")
        
def logout(request):
    auth.logout(request)
    return redirect('LoginReg:index')

beranda/views.py
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404, HttpResponseRedirect
from .models import *
from .forms import *

# Create your views here.
def BlogViews(request):
    posts = Blog.objects.all()
    return render(request, 'index_2.html', {'post':posts})

def BlogDetail(request, slug):
    post = get_object_or_404(Blog, Slug = slug)
    comments = post.comments.filter(Active=True, Parent__isnull = True)
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid:
            Parent_obj = None
            try :
                Parent_id = int(request.POST.get('Parent_id'))
            except :
                Parent_id = None
            if Parent_id:
                Parent_obj = Comment.objects.get(id=Parent_id)
                if Parent_obj:
                    reply_comment = comment_form.save(commit=False)
                    reply_comment.Parent = Parent_obj
            new_comment = comment_form.save(commit=False)
            new_comment.Post = post
            new_comment.save()
            return redirect('beranda:detail', slug)
    else:
        comment_form = CommentForm()

    return render(request, 'blogdetail.html', {'blog':post, 'comments':comments, 'comment_form':comment_form})

homepage/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')

LoginReg/templates/index_1.html
{% load static %}
<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Askcs</title>
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" crossorigin="anonymous">

    </head>
    <style>
        .other1{
            width: 850px;
        }
        .other2{
            width: 150px;
            text-align: right;
        }
        nav{
        background-color:#8DCAFF;
        }
        html{
          background-color: var(--bg-color2);
            color: var(--font-color);
        }
        body{
          background-color: var(--bg-color2);
          color: var(--font-color);
        }
        .jumbotron{
          text-align:center;
          background-color:#CAE9FF;
        }
        p{
          text-align: center;
        }
      </style>
    <body>
      <nav class="navbar navbar-expand-lg navbar-light">
        <a href="{% url 'homepage:index' %}"> <img src="{% static 'images/logoo.png' %}" height="50" width="50"> </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'LoginReg:login' %}" style="color:black">Login <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'LoginReg:registration' %}" style="color:black">Sign up</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'beranda:post' %}" style="color:black">ASK</a>
            </li>
          </ul>
        </div>
      </nav>
      <div class="theme-switch-wrapper">
          <label class="theme-switch" for="checkbox">
              <input type="checkbox" id="checkbox" />
              <div class="slider round"></div>
          </label>
          Dark Mode
      </div></br>
      {% if user.is_authenticated %}
      <p><a style='text-decoration: none; font-size: 32px;'>Hello, {{ user.username }}</a></p>
      <p><a href="{% url 'beranda:post' %}" style='font-size: 40px;'> AYO MULAI! </a></p></br>
      <p><a style='text-decoration: none; font-size: 24px;' href="{% url 'LoginReg:logout' %}">logout</a></p>
      {% else %}
      <p><a style='text-decoration: none; font-size: 24px;' href="{% url 'LoginReg:login' %}">login</a></p>
      <p><a style='text-decoration: none; font-size: 24px;' href="{% url 'LoginReg:registration' %}">register</a></p>
      {% endif %}
      <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>

LoginReg/templates/login.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Askcs | Login </title>
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
         <style>
            nav{
                background-color:#8DCAFF;
            }
            body{
              background-color: var(--bg-color2);
                color: var(--font-color);
            }
        </style>

    </head>


    <body>
<nav class="navbar navbar-expand-lg navbar-light">
  <a href="{% url 'homepage:index' %}"> <img src="{% static 'images/logoo.png' %}" height="50" width="50"> </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'LoginReg:login' %}" style="color:black">Login <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'LoginReg:registration' %}" style="color:black">Sign up</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'beranda:post' %}" style="color:black">ASK</a>
      </li>
    </ul>
  </div>
</nav>
<div class="theme-switch-wrapper">
    <label class="theme-switch" for="checkbox">
        <input type="checkbox" id="checkbox" />
        <div class="slider round"></div>
    </label>
    Dark Mode
</div>

    <div style="margin: 5%; background-color: var(--bg-color2)">
        <form action="{% url 'LoginReg:login' %}" method="POST">
            <p style="font-size: 30px;">Login</p></br>
            {% csrf_token %}
            <div style="display: flex; flex-direction: column; background-color: #F8D9D9; width: 40%; padding: 1%;">
                <div class="form-group">
                    <label for="username" style="color: black;">Username</label>
                    <input type="username" name="username" class="form-control" id="username" style="width: 100%;">
                    </br>
                </div>
                <div class="form-group">
                    <label for="password" style="color: black;">Password</label>
                    <input type="password" name="password" class="form-control" id="password" style="width: 100%;">
                </div>
            </div>
            </br>
            <button type="submit" class="btn btn-primary">login</button>
  
            </br></br><p>Don't have an account? Go to <a href="{% url 'LoginReg:registration' %}">registration</a> page for creating a brand new account</p>
        </form>
    </div>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

LoginReg/templates/registration.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Askcs | Register </title>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <style>
            nav{
                background-color: #8DCAFF;
            }
            body{
                background-color: var(--bg-color2);
                color: var(--font-color);
            }
        </style>
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-light">
  <a href="{% url 'homepage:index' %}"> <img src="{% static 'images/logoo.png' %}" height="50" width="50"> </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'LoginReg:login' %}" style="color:black">Login <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'LoginReg:registration' %}" style="color:black">Sign up</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'beranda:post' %}" style="color:black">ASK</a>
      </li>
    </ul>
  </div>
</nav>
<div class="theme-switch-wrapper">
    <label class="theme-switch" for="checkbox">
        <input type="checkbox" id="checkbox" />
        <div class="slider round"></div>
    </label>
    Dark Mode
</div>
    <div style="margin: 5%; background-color: var(--bg-color2)">

        <form action="{% url 'LoginReg:registration' %}" method="post">
            <p style="font-size: 30px;">Registration</p></br>
            {% csrf_token %}
            <div style="display: flex; flex-direction: column; background-color: #F8D9D9; width: 40%; padding: 1%;">
                <div class="form-group">
                    <label for="username" style="color: black;">Username</label>
                    <input type="username" name="username" class="form-control" id="username" style="width: 100%;">
                    </br>
                </div>
                <div class="form-group">
                    <label for="password" style="color: black;">Password</label>
                    <input type="password" name="password" class="form-control" id="password" style="width: 100%;">
                    </br>
                </div>
                <div class="form-group">
                    <label for="password2" style="color: black;">Confirm Password</label>
                    <input type="password" name="password2" class="form-control" id="password2" style="width: 100%;">
                </div>
            </div></br>
            <button type="submit" class="btn btn-primary">register</button>
            {{ confirm }}
            </br></br><p>Already have an account? Go to <a href="{% url 'LoginReg:login' %}">login</a> page</p>
        </form>
        <div>
            {% for message in messages %}
            <h3>{{message}}</h3>
            {% endfor %}
        </div>
    </div>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

beranda/templates/blogdetail.html
{% load tz %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link href="https://fonts.googleapis.com/css?family=Satisfy&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>ASK-CS</title>
    <style>
    input[type="text"]{
        border: 2px solid blue;
        border-radius: 4px;
        width: 50%;
    }
    input[type="text"]:focus{
        width: 600px;
    }
    button {
        border-radius: 12px;
        background: #ecbebe;
    }
    button:hover{
        background-color: #6372e0;
    }
    nav{
        background-color:#8DCAFF;
    }
    html{
        background-color:var(--bg-color2);
    }
    .jumbotron{
        text-align:center;
        background-color:var(--bg-color2);
    }
    .display-4{
        color:#5F4D48;
        font-family: 'Satisfy', cursive;
    }
    .container-fluid{
        background-color:white;
        height:200px;
    }
    #ask{
	    background-color:white;
    }
    h3{
	    background-color:#617574;
    }
    .sectionpertanyaan {
        margin-top: 20px;
        background-color: #a2abe1;
        padding: 30px;
        margin-bottom: 10px;
        border-radius: 70px;
        float: left;
        width: 50%;
        margin-left: 25%;
        margin-right: 25%;
    }
    .sectionjawab{
        width: 100%;
        border-radius: 70px;
        text-align: center;
    }
    .sectionjawab hr{
        height: 1px;
        background: white;
        width: 50%;
        margin-top: 5px;
    }
    hr {
        height: 3px;
        background: black;
    }
    h1 {
        color: black;
        text-align: center;
        padding: 18px;
        margin: 0 0 10px 0;
    }
    .sectionpertanyaan li{
        background-color: #d2d8fe;
    }
    body{
        background-color:var(--bg-color2);
        color: var(--font-color);
    }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light">
        <a href="{% url 'homepage:index' %}"> <img src="{% static 'images/logoo.png' %}" height="50" width="50"> </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'LoginReg:login' %}" style="color:black; margin-right: 20px; margin-left: 20px">Login <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'LoginReg:registration' %}" style="color:black; margin-right: 20px; margin-left: 20px">Sign up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'beranda:post' %}" style="color:black; margin-right: 20px; margin-left: 20px">ASK</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="theme-switch-wrapper">
        <label class="theme-switch" for="checkbox">
            <input type="checkbox" id="checkbox" />
            <div class="slider round"></div>
        </label>
        Dark Mode
    </div>

    <div style="text-align: center;">
        <h2> {{blog.Title}} </h2>
        <p> {{blog.Content | safe}} </p>
    </div>
    {% if user.is_authenticated %}
    <div class="sectionpertanyaan" style="width: 70%;margin-left: 15%; color: black;">
        <h1>Tuliskan Pertanyaan Kamu !</h1>
        <div style="text-align: center;">
        <form action="." method="post">
            {% csrf_token %}
            <p>Nama :</p>
            {{comment_form.Name}} <br>
            <p>Pertanyaan :</p>
            {{comment_form.Body}} <br><br>
            <button type="submit">Tambah Pertanyaan</button>
        </form>
        </div>
    </div>
    

    <!-- coment untuk pertanyaan -->
    {% for comment in comments %}
        <div class="sectionpertanyaan" style="color: black">
        <div class="section">
            <h4>Pertanyaan dari : {{comment.Name}} </h4>
            <h7><i>{{comment.Created | localtime}}</i></h7>
            <h1><b> " {{ comment.Body }}    "</b></h1>
            <hr>
         </div>
    
        <ul>
        {% for reply in comment.replies.all %}
            <li style="margin-bottom: 10px;"><i> Penjawab : {{reply.Name}} </i>
                <i>[ {{reply.Created}} ]</i>
                <h2 style="margin-left:15px">{{reply.Body}}</h2><br>
                </li>
                <hr>    
        {% endfor %}
        </ul>
        <div class="sectionjawab" style="background:#c2c2e3">
        <p style="font-size: 2vw; margin-bottom: 2px;">Berikan jawabanmu disini !</p><hr>
            <form action="." method="post">
                {% csrf_token %}
                <p style="margin-bottom: 1px; font-size: 20px;">Nama</p>
                {{comment_form.Name}}
                <p style="margin-bottom: 1px; font-size: 20px;">Jawaban</p>
                {{comment_form.Body}}
                <br>
                <input type="hidden" name="Parent_id" value="{{ comment.id }}">
                <button type="submit" style="margin-top: 10px;">Tambah Jawaban</button>
            </form>
        </div>
        </div>
        {% empty %}
            <h4 class="ml-3">Belum ada pertanyaan.....</h4>
    {% endfor %}
    {% else %}
    <div style="text-align: center; width: 50%; background-color: #ecbebe; margin-left: 25%; border-radius: 20px; border-color: black;border-style: dotted;">
        <p><a style='text-decoration: none; font-size: 24px;' href="{% url 'LoginReg:login' %}">login</a></p> <hr>
        <p><a style='text-decoration: none; font-size: 24px;' href="{% url 'LoginReg:registration' %}">register</a></p>
    </div>
    {% endif %}  
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

beranda/templates/index_2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link href="https://fonts.googleapis.com/css?family=Satisfy&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <style>
    nav{
        background-color:#8DCAFF;
    }
    html{
        background-color: var(--bg-color2);   
    }
    .jumbotron{
        text-align:center;
        background-color: var(--bg-color2);
    }
    .display-4{
        color:#5F4D48;
        font-family: 'Satisfy', cursive;
    }
    .container-fluid{
        background-color:white;
        height:200px;
    }
    #ask{
	    background-color:white;
    }
    h3{
	    background-color:#617574;
    }
    body{
        color: var(--font-color);
    }
    </style>
    <title>Category</title>
</head>
<body style="background-color: var(--bg-color2);">
    <nav class="navbar navbar-expand-lg navbar-light">
        <a href="{% url 'homepage:index' %}"> <img src="{% static 'images/logoo.png' %}" height="50" width="50"> </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'LoginReg:logout' %}" style="color:black; margin-right: 20px; margin-left: 20px">Logout <span class="sr-only">(current)</span></a>
                    {% else %}
                    <a class="nav-link" href="{% url 'LoginReg:login' %}" style="color:black; margin-right: 20px; margin-left: 20px">Login <span class="sr-only">(current)</span></a>
                    {% endif %}
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'LoginReg:registration' %}" style="color:black; margin-right: 20px; margin-left: 20px">Sign up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'beranda:post' %}" style="color:black; margin-right: 20px; margin-left: 20px">ASK</a>
                </li>
                
            </ul>
        </div>
    </nav>
    <div class="theme-switch-wrapper">
        <label class="theme-switch" for="checkbox">
            <input type="checkbox" id="checkbox" />
            <div class="slider round"></div>
        </label>
        Dark Mode
    </div>

    <div class="row mt-4 ml-3" style="background-color: var(--bg-color2);">
    {% for data in post %}
    <div class='col-lg-3 col-sm-4 mb-4 mt-10'>  
    <div class="card h-100" style="width: 18rem;">
            <div class="card-body" style="color: black;">
              <h5 class="card-title" style="text-align: center;"> {{data.Title}} </h5>
              <hr>
              <h6 class="card-subtitle mb-2 text-muted">ASK-CS</h6>
              <p class="card-text"> {{data.Content}} </p>
              <a href="{% url 'beranda:detail' slug=data.Slug %}" class="card-link"><span class="badge badge-primary"><b>Masuk Kelas</b></span></a>
            </div>
        </div>
    </div>
    {% endfor %}
    </div>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>